### PR TITLE
Lucas changes

### PR DESCRIPTION
**Pull request by black-calculus**
Big batch of Lucas changes for the time being. Will post the changelog and link to the updated romfs once those are up.

### CODE REVIEW

**Comment by O1yyy** [comment]
PM mag is jc 9 on whiff
- (4) 4 startup frames
- (7) 3 hold frames, first hitbox out for 1st and 2nd frames, 3rd empty 
- (8) frame 1 release box, needs to be in release status for 1 frame to jc it the next
- (9) jc frame on 9th

PM mag is jc 11 on **hitlag**
- (4) 4 startup frames
- (7) 3 hold frames, first hitbox out for 1st and 2nd frames, 3rd empty (NO HITLAG, BUT DOES INCUR HITSTUN)
- (10) frame 1 release box, *2 more hitlag frames, cannot jc in hitlag*
- (11) jc frame on 11th
-------------------------------------------
HDR mag on latest lucas pr WITH HITLAG
- (4) 4 startup frames
- (12) 3 hold frames, **hitlag for 5 frames lmao**
- (16) frame 1 release box, 2 more hitlag frames (hitlag correct here actually), *+1 frame cuz wrong jc frame*
- (17) jc frame on 17th

This mag is jc 10 on whiff instead of f9, so release status's jc window is on f3 instead of pm's f2 (f1 is the hitbox)

oh and another thing, new lucas jab123 electric arc trails still have the punch sfx on it lol
I personally recommend jab 1 and 2 to be pk2's current multihit noise, and 3 can be the classic magic sfx

* Immaculate job on everything else though, from the bottom of my heart thank you for bringing my boi back <3

**Comment by jobrien97** [comment]
Lucas's new PK Rocket behavior:

https://user-images.githubusercontent.com/47401664/169114566-54546fc0-5542-472e-a4df-21e40f50863c.mp4

**Comment by O1yyy** [comment]
I tried my hardest to get specifics on this, but the convo was deleted when we server purged so i lost exact details and screenshots on this tidbit but;

Magnet's hold hitboxes do something funny in PM, 
- the first one does Hitstun ONCE, and then the subsequent looping hitbox doesn't incur Hitstun and just do tick damage
- this special first hit actually has 0 sdi(?) multiplier
- this was done so that you can't simply hold mag on ledge and have the multihit gimp them, but also for some asdi + cc counter measure to make sure holding down and teching the first multihit box doesnt just make magnet unreliable, and actually easily lead into the release hitbox 3 frames later

Calc has said this behaviour was "easily readable and replicatable" when i first brought it up to him, iirc it had to do with some multiplier shenanigan that only applied on first hit? negative kbg maybe?

**Comment by black-calculus** [comment]
Changelog (courtesy of Mad Villain with further details filled in by me):
[Lucas Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/8748959/Lucas.Changelog.txt)

Old/new hitbox comparison (courtesy of Mad Villain):
https://imgur.com/a/11uFWLr

**Comment by black-calculus** [comment]
Closing and merging this PR for now as no issues have been reported from those who have tested it. As far as magnet is concerned I'll have to fine-tune the frame data later.

**Pull request merged**
