### PR TITLE
ICs Rework

### PR DESCRIPTION
**Pull request by SuddyN**
# Ice Climbers Changes

replacement of #1215 

[fighter.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10471412/fighter.zip)

## NEW FEATURES & REWORKS:
- Voluntary SoPo: press shield+special+dtaunt at round start to be rid of Nana for the rest of the match
- Legacy UAir: ICs have their old active single hit UAir back
- Bounce DAir: DAir has been reworked again - now, it's a bounce move similar to YLink DAir.
- Weight-based DThrow
- Spotdodge/roll desync extended to ledge neutral getup/roll
- Handoffs (NANA CAN GRAB)
  - If Popo and Nana are coupled, pressing grab will only grab with Popo, unless you press it again.
  - When Nana lands a grab:
    - You can buffer pummels
    - If not pummeling, Nana will pick a random weighted throw
    - Normal weights:
      - 50% up
      - 20% down
      - 15% forward
      - 15% back
    - Near ledge: (30 units)
      - 60% towards ledge
      - 40% down

## Bug Fixes:
- Nana can now ledgehog (moved to PR #1266)
- Nana is now actionable during Popo throws

### Param Adjustments (closer to P+)
- Weight 92->88
- Dash speed 1.45->1.4
- Run speed max 1.45->1.4
- Walk speed max 1.108->0.95
- Popo and Nana params matched (they were different before !?!?)
  - Popo walk speed max vanilla->0.95
  - Nana ground break 0.0385->0.035
  - Nana air accel x mul 0.06355->0.06
  - Nana air speed x stable 0.91875->0.875
  - Nana landing heavy frame vanilla->4

### FAir
- Hitbox reworked
- Startup f17->f18
- Spike Angle 270->285
- Spike kbg 100->66
- Spike bkb 20->30
- Hilt dmg 12->11

Before:

https://user-images.githubusercontent.com/33226440/212524733-59e0b20d-328f-4d68-ab4a-da16797b4a70.mp4

After:

https://user-images.githubusercontent.com/33226440/214980303-edcaf86d-d4e3-4df8-81e9-d3b06a9895f8.mp4

### BAir
- Shoulder hitbox removed
- Range slightly  reduced

Before:

https://user-images.githubusercontent.com/33226440/212524758-61e48927-b59c-4a43-933b-ebee8cbfe6a0.mp4

After:

https://user-images.githubusercontent.com/33226440/214980318-b1dfe10b-65a0-414c-a0bd-fcde0e94dcfa.mp4

### UAir
- New
- Frame 6
- Last hitbox frame 28
- FAF 35
- Angle 70
- KBG 140
- BKB 10
- Damage 9/7

https://user-images.githubusercontent.com/33226440/213596441-64cad10c-a1cb-4e21-bbcf-8fe2d7b39254.mp4

### DAir
- Causes bounce on hit
  - Bounces less high if hitting shield, to be punishable
- Size slightly reduced
- Landing effect and rumble removed
- Startup f4->f5
- Angle 361->60
- kbg 130->41
- bkb 40->85

Before:

https://user-images.githubusercontent.com/33226440/212524805-92e105d4-fd99-4ff3-acd4-fb53449bfd4f.mp4

After:

https://user-images.githubusercontent.com/33226440/212524029-ea10ad12-986a-49be-8301-321012a9cce9.mp4

### Dash Attack
- Brought up very slighly
- dmg 4.5->9.0
- Angle 80->70
- kbg 60->40
- bkb 80->90
- FAF f42->f40
- This is very close to P+ but a little worse

### Standing Grab
- Size reduced

Before:

https://user-images.githubusercontent.com/33226440/212524833-6ba99b56-0914-4f34-a4e0-1eccd64ec6dd.mp4

After:

https://user-images.githubusercontent.com/33226440/212524095-bcdf66f9-d935-4e01-a46a-08f1c0e8072c.mp4

### FSmash
- Hitbox reworked
- Late/body hitbox dmg 12.5->11
- Effects corrected

Before:

https://user-images.githubusercontent.com/33226440/212524845-a63cf75e-f5fb-4bed-9fd2-e44450381b9c.mp4

After:

https://user-images.githubusercontent.com/33226440/214980344-db094da8-4d0a-4e56-a2ef-2ad1fd5fd89a.mp4

### DSpecial
- Phase 2 dmg 1.8->1.0
- Phase 2 start on projectile travel f4->f2 (phase 3 length adjusted to match travel time)
- Should make it a little harder to freeze unless poing blank
- Phase 1/2 kbg 50->60
- SDI mul 1.5->1.65

### NSpecial
- Startup f15->f18
- Hammer hitbox added
  - dmg 9
  - angle 80
  - kbg 60
  - bkb 80
  - shield dmg 5

New Hitbox:

https://user-images.githubusercontent.com/33226440/212524194-fd27fb4a-f04c-451b-ace8-f30f85193fd3.mp4

### DThrow
- Startup is now weight-based
- FAF f49->f54 on 100 weight (prevents footstool infinites)
- bkb 30-45
- kbg 116->120

### UThrow
- Startup f20->f28

### UTilt
- Hitbox reworked
- Startup f6->f7
- Multihit angle 115->110
- Multihit dmg 0.2->0.5
- Multihit kbg 10->20
- Multihit bkb 65->15
- Final hit f39->f26 (also means less hits)
- Effects emphasize final hit now

Before:

https://user-images.githubusercontent.com/33226440/212524882-1e23f1bd-7adf-4ad6-8209-e9618bb75126.mp4

After:

https://user-images.githubusercontent.com/33226440/212524212-c087c99c-9e48-4bf4-8c71-9e6d84c7327f.mp4

### DTilt
- Shoulder hitbox removed
- Size reduced
- Tipper angle 75->85
- Active frames 4->3

Before:

https://user-images.githubusercontent.com/33226440/212524905-728418c1-1c72-4fa0-b55d-3b1030a9b5c8.mp4

After:

https://user-images.githubusercontent.com/33226440/212524225-d87a1a17-6107-4684-b4b0-2cd2f1381476.mp4

### CODE REVIEW

**Review by SuddyN — COMMENTED** [review]
self-reviewed 1/14/2023 11:50PM EST

**Comment by hdr-balance-backroom** [comment]
Reduce shield damage on Ice Block hammer hitbox
Reduce up tilt's overall damage (deals 22% with both climbers)
Look into reducing Blizzard's freeze chance in some way (one avenue could be to increase the knockback so it has less chance of freezing)

**Comment by SuddyN** [comment]
- [x] Reduce shield damage on Ice Block hammer hitbox
- [x] Reduce up tilt's overall damage (deals 22% with both climbers)
- [x] Look into reducing Blizzard's freeze chance in some way (one avenue could be to increase the knockback so it has less chance of freezing)
  - Note: damage has already been decreased in the mid and late travel frames, which directly influences freeze
- [x] Update the changelog

**Review by techyCoder81 — DISMISSED** [review]
Looked at the attached comparison clips, would suggest fixing the effects on:
- fair, which has significantly less range than the vfx would indicate
- bair, which has somewhat less range than the vfx would indicate
- fsmash, which has significantly more range than the vfx would indicate

**Review by SkewedAskew — APPROVED** [review]
Lgtm

**Pull request merged**
