### PR TITLE
Ganondorf Float Neutral Special

### PR DESCRIPTION
**Pull request by WuBoytH**
For #706

Requires the hdr-assets from [this PR](https://github.com/HDR-Development/hdr-private/pull/15). The files are also included below.
[hdr-assets-ganon-float.zip](https://github.com/HDR-Development/HewDraw-Remix/files/8935904/hdr-assets-ganon-float.zip)

### CODE REVIEW

**Comment by WuBoytH** [comment]
Marked as draft as the functionality is finished, but the animations and cosmetic ACMD are not.

**Comment by kalomaze** [comment]
Fully functional besides the touchups needed for the animations

**Comment by kalomaze** [comment]
Nair glitches out at the end when you use it out of float

**Comment by kalomaze** [comment]
2022061912410900-0E7DF678130F4F0FA2C88AE72B47AFDF

**Comment by techyCoder81** [comment]
(why is this draft?)

**Comment by WuBoytH** [comment]
> (why is this draft?)

I wanted to fix up the grounded start animation.

**Comment by WuBoytH** [comment]
I have fixed up the ground start animation

**Review by techyCoder81 — APPROVED** [review]

**Pull request merged**
