### PR TITLE
Captain Falcon adjustments

### PR DESCRIPTION
**Pull request by SkewedAskew**
Moves were shown and changed accordingly

Changelog: [CaptainFalcon_changes.txt](https://github.com/HDR-Development/HewDraw-Remix/files/9711902/CaptainFalcon_changes.txt)

Hitbox Comparisons: https://imgur.com/a/YVvEiBc

### CODE REVIEW

**Comment by yoonikoo** [comment]
The change to NAIR 1 change it from a dragdown to a pop up at all time. This makes it healthier to vs against. In addition, the raptor boost nerf overall felt really good. There was no reason for Falcon to armor through every move and punish every option with just a Side B. Dash attack changes make it so much easier for opponents to punish it, as it was an insane neutral tool and was super safe to throw it out. It LGTM and is ready to be merged!

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by MadVillainLordQ** [comment]
LGTM

**Review by MadVillainLordQ — APPROVED** [review]
LGTM

**Pull request merged**
