### PR TITLE
Fix projectiles dying inside platforms/ground

### LINKED ISSUE #550: Projectiles spawned inside of ground do not spawn
Running list of projectiles to fix:
- Samus/dsamus/miigunner charge shot
- Samus/dsamus/miigunner missiles
- M2 shadow ball
- Fox laser
- Lucario aura sphere
- Seph flare/megaflare/gigaflare
- ZSS paralyzer
- Shoto Hadouken
- ...

An easy way to reproduce this is to pick falco, go to deadline, and shorthop laser. If you are inside of the platform when the laser comes out, it disintegrates, but if you are outside the platform it goes through it. The intended behavior should be that if the projectile spawns inside of a platform it spawns correctly.

https://user-images.githubusercontent.com/42755519/167160941-0e9b406d-dff6-4f98-bd26-7305de33e26e.mp4

### PR DESCRIPTION
**Pull request by jobrien97**
Projectiles which break/despawn when coming into contact with a surface (Charge Shot, Spacie lasers, Hadouken, etc.) now ignore ground collision, when the ground is flat or near-flat. They will still die on sloped ground.

Resolves #550

### CODE REVIEW

**Review by WuBoytH — DISMISSED** [review]
Why do these funny guys despawn in the first place? The world may never know...

**Comment by yoonikoo** [comment]
[Yooni PR Whoring.xlsx](https://github.com/HDR-Development/HewDraw-Remix/files/9720498/Yooni.PR.Whoring.xlsx)

**Comment by yoonikoo** [comment]
https://user-images.githubusercontent.com/105788245/194197121-934fdae3-4d08-41b7-adb3-4342542564fe.mp4

https://user-images.githubusercontent.com/105788245/194197204-3ad018df-804e-492f-ad7b-b73723558ed7.mp4

**Comment by SirTanknSpank** [comment]
https://user-images.githubusercontent.com/115139386/194241410-0b9c6567-1be4-4c39-9543-f8da974f6330.mp4

**Comment by yoonikoo** [comment]
[Yooni PR Whoring 2.xlsx](https://github.com/HDR-Development/HewDraw-Remix/files/9738314/Yooni.PR.Whoring.2.xlsx)

**Comment by yoonikoo** [comment]
[Yooni PR Whoring 2.xlsx](https://github.com/HDR-Development/HewDraw-Remix/files/9738320/Yooni.PR.Whoring.2.xlsx)

**Comment by O1yyy** [comment]
https://user-images.githubusercontent.com/19886440/194685786-c85171d2-0c04-4350-aaad-7e8fdc4d4841.mp4

bowser jr's ball footage

ecb is simply a Line

**Comment by yoonikoo** [comment]
https://user-images.githubusercontent.com/105788245/194685932-82ca5c2d-a189-4108-9598-89372fad7d20.mp4

**Comment by O1yyy** [comment]
https://user-images.githubusercontent.com/19886440/194686551-a85b5327-a208-4579-ae53-78504c96a626.mp4


krool's ball properly goin through plats but sometimes dying

**Comment by yoonikoo** [comment]
https://user-images.githubusercontent.com/105788245/194688577-ae064e1b-2cd5-4fd5-8e87-4d1706e6ce8d.mp4

updated DDD bug

**Comment by yoonikoo** [comment]
DDD, K. Rool, and Bowser Jr. issues have been resolved :)

**Review by WuBoytH — APPROVED** [review]
If it work it work

**Pull request merged**
