### PR TITLE
Hero changes

### PR DESCRIPTION
**Pull request by black-calculus**
Big batch of Hero changes for the time being. Will post the changelog and link to the updated romfs once those are up.

### CODE REVIEW

**Comment by black-calculus** [comment]
Changelog:
[Hero Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/8714286/Hero.Changelog.txt)

motion_list changes for Hero (to be merged in alongside this PR later):
[hero motion list.zip](https://github.com/HDR-Development/HewDraw-Remix/files/8714299/hero.motion.list.zip)

**Comment by yoonikoo** [comment]
The Hero changes are very significant. The nerfs to the MP usage is completely fine. However, the removal of dash cancelling on neutral B and the NAIR nerfs from frame 8 to 7 were unnecessary.

**Comment by Riah321** [comment]
- Put dash cancel back on fireball 1 and reduce the cost to 8.
- Revert nair frame data nerf.
- Increase fair horizontal range
-  Dash attack doesn't have proper risk/reward proportions.

His aerials feel clunkier than they already did and they were pretty clunky. In order to justify the frame data nerfs he needs bigger coverage in front of him otherwise keeping opponents out will be impossible. Removing dash cancel on the light version of fireball makes it useless, but then it also is way too expensive. 
I forgot to mention that the nair is because he needs at least 1 (one) get off me tool if he's going zone after losing neutral the first time.

**Comment by black-calculus** [comment]
Made a few more changes, the changelog from the previous iteration of the PR and the full current changelog are attached:
[Hero Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/8720451/Hero.Changelog.txt)
[Hero Changelog (Full).txt](https://github.com/HDR-Development/HewDraw-Remix/files/8720450/Hero.Changelog.Full.txt)

Further readjustments will have to come later as there are 30 other characters I need to address for the time being.

**Comment by Riah321** [comment]
Ship it :)

**Pull request merged**
