### PR TITLE
Falco slight rework

### LINKED ISSUE #920: Falcos slight rework and polish
Nerf up air to be five active frames and shrink all hitboxes ✅

Increase the start up by 2 frames and FAF of up tilt by 2 frames (possibly add hand intangibility) also give up tilt a less favorable combo angle(75?)✅

Shine angle and KB adjustments. Probably lowering BKB and the angle being slightly more vertical to incentivize shine over up tilt as the main combo tool☑️(angle will be left alone until DDI is more solidly hashed out)

Reducing the BKB of nair to allow for linking into shine more consistently(also nair edge cancel combos just don't really exist rn) and tweaking the KBG to ensure that it can secure kills offstage☑️(Nairs weak hit has no BKB so unsure of how to create slideoff combo potential. Also not a vital feature)

Shrinking the hitboxes of falco fair and increasing the start up of fair. Currently its frame 3 and it should be more frame 5✅

Increasing the startup of down tilt so that drag down fair can still be used as a combo tool but won't easily combo into down tilt✅

Alter down air to give it melee damage stats while trying to maintain its KB stats for the most part. Maybe increasing BKB and reducing KBG✅

Adjusting Ftilt to be more in line with fox’s✅

### LINKED ISSUE #928: Falco nair rumble
giving falco rumble like fox nair on his current nair instead of the old rumble

### PR DESCRIPTION
**Pull request by TeamPearson**
resolves #920 
resolves #928

### CODE REVIEW

**Comment by TeamPearson** [comment]
Effects have yet to be updated but I am planning on motionrating any effect script to match what falco is doing

**Comment by WuBoytH** [comment]
> Effects have yet to be updated but I am planning on motionrating any effect script to match what falco is doing
> 

Just to make sure, if you've motion rated the game ACMD, you don't need to motion rate the effect ACMD too

If you're referring to the individual effect calls then sure yeah go for it

**Comment by yoonikoo** [comment]
The changes to Falco in this PR look good to me. Future adjustments may be need in the future whenever new gameplay changes are made. Now all the Falco complainers can STFU about Falco being busted (even though he wasn't even busted at all prior).

**Comment by TeamPearson** [comment]
> > Effects have yet to be updated but I am planning on motionrating any effect script to match what falco is doing
> 
> Just to make sure, if you've motion rated the game ACMD, you don't need to motion rate the effect ACMD too
> 
> If you're referring to the individual effect calls then sure yeah go for it

actually yeah upon looking back at all the moves the effects are all fine. I just assumed they needed adjustment. Otherwise these changes are ready to ship!

**Review by WuBoytH — DISMISSED** [review]

**Review by WuBoytH — APPROVED** [review]

**Pull request merged**
