### PR TITLE
Incineroar changes

### PR DESCRIPTION
**Pull request by black-calculus**
Big batch of Incineroar changes for the time being. Will post the changelog and link to the updated romfs once those are up.

### CODE REVIEW

**Comment by SkewedAskew** [comment]
Lgtm

**Comment by Riah321** [comment]
- Change up B instant dive to an A+B input
- Side B needs a belt grab hitbox
- Jab 3 needs a spike hitbox on thumbs down. Activate on whiff with taunt?
- Give side taunt projectile invincibility when he sticks his chest out
- Give up taunt the ability to charge revenge by 0.3% (any minuscule amount)

Instant dive is really janky and inconsistent. Giving it an A+B input would fix these issues.
Neutral side special can just go through players sometimes. Giving him a belt hitbox would make it more consistent.
Taunt changes are because he is not BM enough yet.

**Comment by black-calculus** [comment]
motion_list changes for Incineroar (to be merged in alongside this PR later):
[Incineroar motion list.zip](https://github.com/HDR-Development/HewDraw-Remix/files/8748453/Incineroar.motion.list.zip)

**Comment by black-calculus** [comment]
Updated changelog with some errors corrected:
[Incineroar Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/8748576/Incineroar.Changelog.txt)

**Pull request merged**
