### PR TITLE
Fox adjustments

### LINKED ISSUE #1083: Fox tuneup
Give fox bair and nair melee style kb ratios with sakurai angle as a platform to test out how sakurai angles can interact with new DDI

Give fox melee dair. Larger hitbox weak spike with no launcher

General hitbox size adjustments(upsmash and up air, nair hitbox adjustment, probably all smash attack will be looked at)

Upthrow having a bit less endlag in order to better convert off of (compensation for previous hitstun adjustments)

Add F1 shine cancelable on F4 with balancing around hitbox size and values

Reevaluating up and down tilt properties

### PR DESCRIPTION
**Pull request by TeamPearson**
Resolves #1083 

F1 shine cancellable on frame 4

added right leg nair hitbox
Nair KBG: 92>100 BKB: 25>10

Bair angle: 40>361 
(Strong hit) KBG: 95>110 BKB: 20>0
(Weak hit) KBG: 90>110 BKB: 15>0

up tilt and down tilt reworked 
>up tilt hitbox priority reversed
>up tilt kb changed to KBG: 130 BKB: 30
>down tilt KBG: 110 BKB: 20

fox drill replaced with melee drill

hitbox on up air, upsmash, and Fsmash shrank

upthrow FAF reduced by 3 frames 

shine kbg increased by 10 all characters should be put into tech in the 60-80% range

Old hitboxes:
image
up air 1
image
up air 2
image
F smash
image
upsmash
 image
up smash weak
image

New: 
up air 1
image
up air 2
image
F smash
image
Up smash
image
Up smash weak
image

### CODE REVIEW

**Comment by Kaiokendo661** [comment]
Very solid changes that also feel good to use!

**Comment by yoonikoo** [comment]
The changes are exactly what Fox had lacked and needed desperately, Making his DAIR a true drill really fixes a lot of issues, as Fox now has optimal shield pressure (alongside F1 shine) and has a move that cracks open opponents. With Fox as the monster that he is with F1 shine, it was only fair to have his smash hitboxes reduced. Uptilt and downtilt adjustments were well needed to put opponents exactly where Fox wants them, in the air. Reverting the upthrow to its former glory, the Fox is back in business with upthrow juggles on fastfallers and for DI reads with BAIR or UPAIR. Fox is a really fun character to use now and is not clunky at all. LGTM, its merge this bread.

**Comment by Ruuufiooooo** [comment]
drill actually converting and giving you more options/conversions is sick! nothing stands out as being busted/too strong, just working as intended lol lgtm!

**Comment by elias-michaias** [comment]
Dtilt and Utilt knockback feel a little weak; other than that, this is full of really good changes. Feels so amazing to have shine back. Bless you Pear.

I understand that the way Fair's animation works may be a little wonky, but if you DO happen to find a way to adjust fair to work more smoothly, that would be phenomenal. No expectations on that one though! All in all, absolutely fantastic PR.

**Review by HisashiASM — DISMISSED** [review]
LGTM!
Fox is Melee now baybee

**Comment by SkewedAskew** [comment]
Lgtm

**Review by SkewedAskew — APPROVED** [review]
Lgtm

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Pull request merged**
