### PR TITLE
New Turbo Mode gamemode (next to tag)

### PR DESCRIPTION
**Pull request by techyCoder81**
- This adds turbo mode as a game mode next to tag. 
- Currently it still needs a relevant `.webp` file to show for the video.
- you can cancel anything as long as it hit the opponent, currently with no restrictions
- open to suggestions for improvements

### CODE REVIEW

**Comment by WuBoytH** [comment]
> * you can cancel anything as long as it hit the opponent, currently with no restrictions

I will say that this won't be true for every move, mostly special moves. You won't be able to cancel Mario's Up B on hit for example if you just call `CancelModule::enable_cancel`.
If you *do* want cancels into literally anything, you will also need to run `fighter.sub_wait_ground_check_common(false.into())` and `fighter.sub_air_check_fall_common()`.

**Comment by kalomaze** [comment]
[01654892217_01006a800016e000.log](https://github.com/HDR-Development/HewDraw-Remix/files/8882052/01654892217_01006a800016e000.log)
Crashes after starting the game on the CSS, you can audibly hear the crowd cheer cut out as it freezes
Same happens to tag mode and even if you're playing normally

**Comment by kalomaze** [comment]
Fully functional now, and also very funny

https://user-images.githubusercontent.com/66376113/173161640-57aa8369-6abb-473d-a1a2-3e3db71baab4.mp4

.

**Comment by kalomaze** [comment]
The only issue I've found so far is that for transformation characters like Pokemon Trainer and Pyra/Mythra, only the character that was loaded in first gets turbo cancels

**Comment by kalomaze** [comment]
Attempting to create a webp for this and adjusting the html to fit doesn't seem to work when I tried. No webp loads ingame for  turbo mode, for whatever reason, even though the resolution is identical and the file size is lesser than tag's webp
Here's the edits
[docs.zip](https://github.com/HDR-Development/HewDraw-Remix/files/8885495/docs.zip)

Also pythra/transformation characters work now (note: on nightly both ivysaur and pyra apparently cause crashes tho lol)

**Comment by techyCoder81** [comment]
this is ready for test and review.

**Comment by kalomaze** [comment]
lgtm

**Review by blu-dev — APPROVED** [review]
lgtm

**Pull request merged**
