### PR TITLE
Various Terry Bug-Fixes

### LINKED ISSUE #752: Terry suffers random heart failure when attempting to use EX Burn Knuckle.
When Terry attempts to do EX Burn Knuckle, he will slow down immensely in place and be left vulnerable for about 30-40 frames before actually doing the charge forward at normal speed. 

Easily recreated on current nightly with just doing EX Burn Knuckle at any time, air or ground.

### LINKED ISSUE #860: Terry forgot to eat his vegtables before using his EX Specials
Terry currently has an issue where when calling for EX Specials, he does not actually call their properties such as damage, KB angles, etc. Can be noticed with damage values for Burn Knuckle (10 and 13 instead of 20), Crack Shoot not spiking on all hits, and Volcano Power Dunk not existing. 

Good luck.

### PR DESCRIPTION
**Pull request by WuBoytH**
Resolves #752
Also resolves #860 

Fixes Terry's Cardiac Arrest issue *and* his lack of vegetables in his diet.

### CODE REVIEW

**Comment by CrossSockDance** [comment]
Unfortunately no changes have happened in game. Thank you so far for your efforts and hopefully we can get to the bottom of this mystery.

**Comment by WuBoytH** [comment]
GitHub actions broke so: [plugin.zip](https://github.com/HDR-Development/HewDraw-Remix/files/9162034/plugin.zip)

**Comment by CrossSockDance** [comment]
Success! Terry's EX specials work again!

**Review by HisashiASM — APPROVED** [review]
LGTM, all is nice.

**Pull request merged**
