### PR TITLE
Wario Shake Up Adjustments

### PR DESCRIPTION
**Pull request by CSharpM7**
Assets: 
[hdr-wario-assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/12165610/hdr-wario-assets.zip)

# Overview
A mix of aesthetic changes and changed moves, this PR gives Wario more moves based on his Wario World incarnation. His new back air retains most of the properties of the old one, just trading startup for wider range. Down air is the familiar Ground Pound from PM, with a new animation and a landing hitbox. Forward Throw is now a simple toss forward, with higher damage. Up Throw his the signature piledriver, capable of KOing opponents at higher percents. Down Throw has now been reworked to be very similar to the old Up Throw, retaining most of its incredible properties for comboing into Waft, Up Air, Up B...pretty much everything huh...

## Down Smash
downsmash

PM's Ground Shake attack, this combo-starter smash attack has a relatively large range and grants decent advantage on hit. 
```diff
! New Move: Ground Shake
! Active: 10-13
! Damage: 17(ground)/15(air)
! Angle: 275/80
! KBG: 25/80
! BKB: 100/25
! FAF: 43
```

## Back Air
bair1
bair2
bair3
bair4
```diff
! New Animation that increases vertical range of this move
- Startup: 9->13
```

## Down Air
dair1
dair2
dair3
dairland

```diff
! New Move: Ground Pound
! Active: 15-18,18-44
! Damage: 12/10
! Angle: 270/60
! KBG: 75/95
! BKB: 50/30
+ Can bounce off of opponents
! Bounce FAF: 45
```

## Pummel
```diff
! Shake-it pummel from previous PR
```

## Forward Throw
```diff
! New Animation based on Mega Toss
+ Damage: 4->8
+ Angle: 45->30
! KBG: 65->80
! BKB: 60->60
```

## Back Throw
```diff
- Can no longer move Wario after the opponent has been thrown
```

## Up Throw
https://user-images.githubusercontent.com/13909643/231276633-11b04701-be6d-49bb-b93a-1fafe13de397.mp4
```diff
! New Move: Piledriver
! Has a larger, stronger collateral hitbox for larger opponents
! Slightly slows down the animation for heavier opponents
! Damage: 11
! Angle: 80
! KBG: 95
! BKB: 80
```

## Down Throw
```diff
! This move now has properties identical to old up throw
! Angle: 50->89
! KBG: 130->135
! BKB: 50->60
- FAF: +2
```

### CODE REVIEW

**Review by SuddyN — DISMISSED** [review]
thanks for comments

**Review by hdr-balance-backroom — CHANGES_REQUESTED** [review]
- Lower late dash attack angle
- Down air spike should be weaker against aerial opponents
- Allow dash attack to continue off edges

**Review by hdr-balance-backroom — DISMISSED** [review]
- Reverse the damage priority of bair hitboxes (hand > arm > shoulder), increase hitbox sizes, and improve the autocancel window to allow Wario to autocancel bair in a shorthop
- Reduce uthrow KB (Make it weaker than Mewtwo uthrow for reference)
- Improve the visual of uthrow to make it more impactful (we suggest to increase the speed of the rise and fall portions of the animation). Use the COLLISION_SOUND_ATTR_HEAVY to give the move more impact
- Lower late dash attack angle
- Dair spike should be weaker against aerial opponents
- Allow dash attack to continue off edges

**Review by SkewedAskew — APPROVED** [review]
Wah

**Pull request merged**
