### PR TITLE
Young Link Roll Dash Attack

### PR DESCRIPTION
**Pull request by chrispo-git**
Romfs: [hdr-assets-pr.zip](https://github.com/HDR-Development/HewDraw-Remix/files/9814516/hdr-assets-pr.zip)

Gives Young Link a rolling Dash Attack:
Startup - 6
Active frames 6-10/11-21 (early/late)
Damage - 11/8 (early/late)
Angle - 70/85 (early/late)
BKB - 80/70 (early/late)
KBG - 40
FaF - 35
During active frames, Young Link can jump off the edge. After frame 26, he simply rolls off the ledge

https://user-images.githubusercontent.com/69305550/198138807-a7518e31-5abf-42e3-8c2e-4579d3720b1d.mp4

### CODE REVIEW

**Comment by WuBoytH** [comment]
if you want him to roll off but not keep his dash attack motion, you don't disable ENABLE_FALL, unless of course your code allows him to roll off after frame 26 *despite* disabling ENABLE_FALL, in which case that's a mistake on my part.

**Comment by chrispo-git** [comment]
> if you want him to roll off but not keep his dash attack motion, you don't disable ENABLE_FALL, unless of course your code allows him to roll off after frame 26 _despite_ disabling ENABLE_FALL, in which case that's a mistake on my part.

He can still roll off after frame 26, despite disabling ENABLE_FALL. I assumed it was a mistake yeah

**Comment by WuBoytH** [comment]
> > if you want him to roll off but not keep his dash attack motion, you don't disable ENABLE_FALL, unless of course your code allows him to roll off after frame 26 _despite_ disabling ENABLE_FALL, in which case that's a mistake on my part.
> 
> He can still roll off after frame 26, despite disabling ENABLE_FALL. I assumed it was a mistake yeah

If you want to keep that behavior, I have a bugfix PR out now, make sure to remove the line that turns off ENABLE_FALL

**Comment by chrispo-git** [comment]
> > > if you want him to roll off but not keep his dash attack motion, you don't disable ENABLE_FALL, unless of course your code allows him to roll off after frame 26 _despite_ disabling ENABLE_FALL, in which case that's a mistake on my part.
> > 
> > 
> > He can still roll off after frame 26, despite disabling ENABLE_FALL. I assumed it was a mistake yeah
> 
> If you want to keep that behavior, I have a bugfix PR out now, make sure to remove the line that turns off ENABLE_FALL

Honestly I'd rather it go

**Comment by hdr-balance-backroom** [comment]
Please increase the KBG and add around 5-6 more frames of endlag. The late hit is very safe on shield at -10, and the move itself combos far too easily (keep in mind this is an edge-cancelable burst option)

**Comment by chrispo-git** [comment]
> Please increase the KBG and add around 5-6 more frames of endlag. The late hit is very safe on shield at -10, and the move itself combos far too easily (keep in mind this is an edge-cancelable burst option)

FaF increased 35 -> 40
KBG increased 40 -> 78


lmk if KBG needs to be increased further

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Review by SkewedAskew — APPROVED** [review]
Lgtm, let's roll

**Pull request merged**
