### PR TITLE
Zelda Cohesiveness Adjustment : Phantom Hitcancel, Dins Fire, Ftilt Normalization

### PR DESCRIPTION
**Pull request by Z-hime**
The goal of this PR is to tie her overall kit together more neatly and increase her skill ceiling. 
Several gameplay elements, particularly her specials, have been reworked to function together and create a new dynamic for MV's original Hitcancel Phantom (HCP) and Askew's Din Mines.
This build aims to increase Zeldas overall efficiency in skilled hands when traps are properly set and conditions are fulfilled.

Side note: Thanks to everyone who chipped in while I toiled over this one trying to get it right - Askew, JOB, Hisashi, Yooni & Jaccob <3

**PR is ready for playtesting and review.**

-----------------------------------------
                    SPECIALS
-----------------------------------------

**Phantom:**

The Phantom spawned a bit too close to Zelda and she would clip through it's model.
Regular phantom has been shifted back more similarly to Ultimate.
Note: I believe the intention was to enable phantom cancel combos by bringing the phantom a bit closer to her body, but new hitcancel phantom positioning (HCP) has resolved this. 

[-] Pos offset x:  1.0 -> 1.6

Phantom Position - 1 6 offset X Axis

[R] Due to Phantom being pushed back further behind Zelda by 0.6 units, compensation was needed to maintain original Phantom striking distance:

[R] Phantom Rush Speed 1:  4.0 -> 4.5
[R] Phantom Rush Speed 2:  4.5 -> 5.0
[R] Phantom Rush Speed 3:  5.0 -> 5.5
[R] Phantom Rush Speed 4:  5.5 -> 6.0
[R] Phantom Rush Speed 5:  6.5 -> 7.0

**[R] Hitcancel (Grounded only) :**

Phantom Position Hitcancel Ground

https://user-images.githubusercontent.com/118575626/221392132-431d0e72-e1c7-4bab-856d-ad13acd8bc92.mp4

**Further Adjustments to Phantom Utility**

[=] Platform Drop window added during charge state:  _**Order of operations**_ prevented this tech from being possible and is now coded in to function properly.
[=]  As noted above, phantom will now catch platforms and not fall through them when spawning. **Holding the stick down** will allow phantom to pass through the platform with Zelda - _**For Order of OP**_
[+] Phantom 4 - KBG 40 - > 60 - Creates better bounce from spike hit to allow for proper followup. Growth was too low given Zeldas slower speed and she was unable to capitalize.
[+] Phantom 5 - KBG 80 - > 90 - Phantom 5 was not killing Palutena with DI until 170%. This move should kill at a more approriate range. Also of note, Phantoms 1-4 are used mostly as setup for Zelda herself to score a KO. Phantom 5 given its charge time, was rarely optimal to use. This should put it in a range where it will be a bit more threatening, but not overwhelming.

**Dins Fire:**
Bang timer has been increased and higher angle emphasizes accuracy of placement.
Dramatic speed reduction to assist with precision.

[!] Gfx adjusted to always match size of hitbox on last tick
[-] Speed: 2.0 - > 1.25
[-] Speed Max 8 - > 2.75
[+] Angle Max: 3.0 - > 6.0
[R] No Bang: 3 -> 4 (extra tick)
[R] Bang timer:  120 -> 180 
[R] Life: 50 -> 60
[R] Count: 50 - > 60

New Max Distance - Cast distance is closer to Zelda due to Speed change:

https://user-images.githubusercontent.com/118575626/219971523-ffe31dc2-ddf6-4f7e-ab7b-457a3af01578.mp4

New Angle - Angles allow for more precision

https://user-images.githubusercontent.com/118575626/219971527-af4a330b-2568-48ec-a515-835697ed2106.mp4

-----------------------------------
                NORMALS
-----------------------------------

**Ftilt Low**
Normalized with other tipper hitboxes on Uftilt and Ftilt, inner hits still send outwards for proper tech chase.
[R] Angle: 40 - > 130
Ftilt Angle -Arm1, hand1, tip1  - Angle 130

**Up Air**
Kbg on inner and outer hits have been swapped. Inner hit, the smaller hitbox, is now the higher KB. The move had several windows where it felt like it should kill but fell short. Also promotes accuracy of hitting with the smaller hitbox on this move. 
[R] Inner: KBG 68 - > 70
[R] Outer: KBG 70 - > 68

**Usmash**
Similarly to Uair, usmash was falling short of killing when it should be. Small adjustment for slightly earlier kills.
[+] Final Hit KBG 218 -> 220

### CODE REVIEW

**Comment by yoonikoo** [comment]
Played with Zhime. LGTM. Changes are not too overbearing in game since the boom timer gives both players more time to react.

**Comment by Botodob** [comment]
Have played on this PR and have been keeping close tabs on it to make sure the vision of the character was being handled with care.
I can comfortably say that nothing here feels out of pocket, and better actuallizes the original ideas given from the character, and it feels like its meant for people who truly want to dig their teeth into the character.
Starting with Dins changes.
The increased size on max is great and would seem insane, but due to the length of time it takes for it to go off, it is much less about the opponent falling into it, and moreso timing your pushes to match your dins, and the opponent plays around it, making it fit much more with her trapper vision.
With current beta dins, it feels more like "Throw this out to cover space, then setup or punish agro" where as with this patch, it does not cover space close to zelda nearly as threateningly due to the delayed timer, which nerfs that aspect of the character, but benefits the methodical side instead.
The decreased length and speed of dins along with the maneuverability is great as it allow for applicable usage of max size dins.
Not even remotely overpowered, just different and much harder to use. Will take much time to truly master.

Phantom changes just feel like quality of life. While it is still good in beta, its more good as a wall, not as a threat. Here it feels more like a threat and balances out the character. Also feels harder to setup well due to the changes to dins.
Hitcancel on the phantom placing in front seems insane at first glance, until you realize that upon activation for phantoms, the hitbox is a windbox on 3-5, making the only real threat of being hit 1-2, which arent great. This nerfs phantom cancels on shield, making it a much more situational move, but also better for comboing, which is what the concept feels like it was built for in the first place. 

The changes to the rest of the moves feel in line and arent insane by any means, just feel more cohesive to her kit. Upsmash was weak, and up air was over nerfed, and these changes compensate for those things.

Overall final statement is this feels great and I hope it gets added to beta.

**Comment by FSFrozen** [comment]
Overall a successful refinement of Zelda's kit from previous versions, kill power feels more in line with what she should have and the special adjustments allow for more flexibility in her setups. A great improvement!

**Comment by jaccob101** [comment]
Feels like it makes her gameplay more distinct and nothing feels out of place

**Comment by MosaMosa-x** [comment]
Great additions to her kit, really make her feel more rewarding to play for thinking ahead. Also really loving phantom plat-drop as I feel like its an underrated change

**Review by hdr-balance-backroom — DISMISSED** [review]
- Resolve bug where phantom can get the altered spawn when very close to the ground
- Revert Din's Fire max size increase

**Review by HisashiASM — COMMENTED** [review]
Code looks good
Now onto the other stuff, get at 'em backrooms!

**Review by HisashiASM — APPROVED** [review]

**Review by HisashiASM — DISMISSED** [review]

**Comment by HisashiASM** [comment]
Baka

**Comment by Botodob** [comment]
The changes to dins done over the past couple of days do not feel great for the character. With the addition of dins as it was originally designed by Zhime, the character felt unified in their design. Whereas with these new changes to dins, it feels as tho she is lacking in potential with dins. The hard part should not be placing dins, and the speed change makes this move harder to setup. The size change is one that feels whole-ly out of place. making the size 3 here, when the size in vanilla smash is 3.8 at max. It feels like a lot of our feedback and people who played against this characters feedback was not taken into account when these changes were made. Making the size larger or even the same as vanilla will not affect this move too much considering the considerable time the opponent has to play around the explosion.  all in all, i feel like the character should receive a buff to the speed and the size of this move from this current version. Once it gets pushed to beta, if it is felt to be too broken, which given zelda's kit, it will be new for people to deal with, but people will learn how to play around it, then it should be changed from there. This just buffs her kit and current playstyle while still keeping her weaknesses very prevalent. She needs a larger dins with the timer shown. I think letting this version thru in its strongest form would really help us to know whether or not it needs to be toned down rather than changing it here and then buffing it later. Please feel free to start a discussion with me here, I would love to hear the reasoning behind these changes.

**Comment by jaccob101** [comment]
Love the direction her playstyle takes with these changes, the up smash/air are good qol. It's unfortunate that Zelda isn't more rewarded for the risk and commitment she takes while charging dins the full distance, as you basically have to sit at ledge for like 5 seconds only for it to be smaller than vanilla. I still like the concept way more than nightly's dins though

**Review by SkewedAskew — APPROVED** [review]
Lgtm

**Pull request merged**
