### PR TITLE
Greninja Tweaks

### PR DESCRIPTION
**Pull request by elias-michaias**
If installing manually, make sure to download and extract [greninja-assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/11928694/greninja-assets.zip) and place it in the `hdr-assets` folder on your SD card. Otherwise, you should be able to automatically install this properly through the HDR Launcher. 

Click here to see the [changelog](https://github.com/HDR-Development/HewDraw-Remix/files/9994377/changelog.txt).

NOTE:
Substitute currently has a 100% log spawn rate (will not spawn doll) due to doll having certain problems. This will be reverted when doll becomes fully functioning.

### CODE REVIEW

**Comment by elias-michaias** [comment]
[greninja.zip](https://github.com/HDR-Development/HewDraw-Remix/files/9986378/greninja.zip)
Here are the necessary romfs additions. Place it in the "ultimate" folder on your SD card.

**Comment by Riah321** [comment]
I'm not affiliated or anything, but you should probably move Ftilt and Dtilt hitboxes inwards and clean them up along with the water pulse effects being moved to the foot. They're pretty egregiously large and one of the devs said they thought it was a good idea awhile back when talking about balance.
Fair sourspot/sweetspot could also use a touchup.
Removing the jump cancel on dair was also something that was mentioned by the devs. Just an idea I personally had, but removing the stall and fall but keeping the bounce would make for a more interesting tool.
Adding a shield cancel before release in lieu of removing the dash cancel would also add more versatility and mixup potential to the move in this more movement based game.

Jab is also kind of goofy and can whiff when trying to jablock. Please reduce the size of this effect and add jablock hitboxes :)
2023020800421400-0E7DF678130F4F0FA2C88AE72B47AFDF

**Comment by WuBoytH** [comment]
Closed due to inactivity - reopen when work picks up again

**Comment by elias-michaias** [comment]
Development resumes!

**Comment by WuBoytH** [comment]
Outdated, and should be updated before it gets opened again, if it does.

**Pull request closed without merging**
