### PR TITLE
Robin Linking Improvements, UAir/DAir Levin Change, Throw FAF Decrease

### PR DESCRIPTION
**Pull request by jaccob101**
Arc Fire now connects with no di or sdi, 30% shorter duration to make confirms less free and to control less space. Jab 123 now links better. Up air and down air act like other aerials and Levin is given at start of game. Throws feel better to use and confirm better.
Misc:
~[+] Robin now spawns with Levin, Up Air and Down Air do not switch to bronze automatically at the end. QoL
Down Throw:
~[+] FAF from 37 to 35
Up Throw: 
~[+] FAF from 47 to 44
Arc Fire: 
~[-] Total duration of pillar from 50 to 35 (30% shorter)
Arc Fire Rise: 
~[+] Angle from 85 to 96
~[+] Shield damage from -0.6 to -0.5
Arc Fire Burn:
~[+] Angles from 85 to 120 and 115 (first and second hit)
~[/] Rehit from 8 frames to 4
~[+] Shield damage from -0.6 to -0.5
~[-] Duration from 30 frames to 15
Rapid Jab:
~[+] Angle from 361 to 65 (more vertical)
~[+] BKB from 11 to 9 (less pushback)
~[+] Hitstun modifier from +2 to +3 (compensates for above changes)
~[+] SDI multiplier from 0.6x to 0.4x (should hit a couple times before SDI escapes)
Rapid Jab Finisher:
~[+] Active frames from 1 to 3 (didn't connect properly before)
Jab 1:
~[-] Hitlag modifier from 1.0x to 1.1x (easier sdi)
Jab 2: 
~[+] BKB from 20 to 27 on tipper hitbox
~[+] Pull Hitbox from angle 180 to 135 and now highest priority, so that jab 2 only pushes away if the opponent is close.
~[-] Hitstun Modifier from +2 on pull hitbox to 0
~[-] Hitlag modifier from 1.0x to 1.1x (easier sdi)
Jab 2 Tipper Hitstun Frames:
Nightly: 17 frames at 0, 19 at 100%
PR: 18 frames at 0, 20 at 100%

### CODE REVIEW

**Review by SkewedAskew — CHANGES_REQUESTED** [review]
Avoid using additional hitstun wherever possible. For jab, you'll need to find a balance of BKB and KBG so as not to give it too much frame advantage while still being able to reliably connect

**Review by hdr-balance-backroom — CHANGES_REQUESTED** [review]
- Increase hitlag on jab1 and/or jab2 to 1.1-1.2
- Speed up Arcfire burn
  - With the higher consistency, this lets it be more useful in combos but mitigates it being a free smash attack confirm
- If you can get Levin Sword to spawn on match start, then feel free to add it
- Increase jab finisher activity by 1 frame

**Comment by jaccob101** [comment]
It's been like 2 weeks did you have any more changes you wanted made?

**Comment by jaccob101** [comment]
> * Increase hitlag on jab1 and/or jab2 to 1.1-1.2
> 
>     * Speed up Arcfire burn
>       
>       * With the higher consistency, this lets it be more useful in combos but mitigates it being a free smash attack confirm
> 
>     * If you can get Levin Sword to spawn on match start, then feel free to add it
> 
>     * Increase jab finisher activity by 1 frame

--------------------------------
It's been like 2 weeks were my changes not satisfactory or did I not follow a process to get it re-reviewed?

**Review by hdr-balance-backroom — DISMISSED** [review]
- Arcfire's hitbox duration was sped up, but the visual effects still matches the previous version

**Review by SkewedAskew — APPROVED** [review]

**Pull request merged**
