### PR TITLE
Mewtwo Upthrow and Aerial Disable Adjustments

### PR DESCRIPTION
**Pull request by yoonikoo**
[changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/9743640/changelog.txt)

Adjusted Mewtwo upthrow to better combo/act out of it. Aerial disable now has utility.

### CODE REVIEW

**Review by HisashiASM — DISMISSED** [review]
Remove lua comments, helps keep the code clean :)

**Review by HisashiASM — COMMENTED** [review]
All good, now lets see a quick test from someone and I say we are good to push?

**Comment by yoonikoo** [comment]
> All good, now lets see a quick test from someone and I say we are good to push?

Hopefully Skudo can test this with me ASAP.

**Comment by skudo4president** [comment]
> All good, now lets see a quick test from someone and I say we are good to push?



> All good, now lets see a quick test from someone and I say we are good to push?

These changes are pretty great. Mewtwo can now mixup his aerial game with down special, giving his aerial game more versatility without it being too broken. He can also get things going now with up throw at low percents. And use down throw at mid percents to tech chase. Now all of his grabs have a unique purpose. Back throw kills and forward throw racks up good damage.

**Comment by Bottz-3** [comment]
Up throw has finally gained extra combo potential for fastfallers and juggling potential with it for other weight classes, which was made much easier with the reduced FAF. Aerial confusion kills Inkling on Small Battlefield, on the right platform at about the 120% range. Feels like it has reasonable kill power, given that it's main usage will be used for killing off the side. 

PR feels great to use- and from my testing, without any overadjusted values.

**Review by SkewedAskew — APPROVED** [review]
LGTM

**Pull request merged**
