### PR TITLE
Falco Adjustments 2 Return of Jafar

### LINKED ISSUE #1057: Falco F1 shine
people have been asking about this lately like a lot. Its relatively quick and easy to do and Ive already compiled a lot of research for this so I went ahead and made it.

shine hitbox comes out of  F1
shine is jump cancelable on F4
hitbox has been shrank and repositioned to better match past iterations of the move
SDI multiplier lowered

### LINKED ISSUE #1138: Falco Nair and Bair nerfs
Falco Nair 
strong hit:

Angle: 40>361
bkb: 109>100
kbg:17>10

weak hit:

bkb:80>90
kbg: 0>15

Falco Bair
strong hit:

angle: 40>361
bkb: 15>0

weak hit:
kbg:100>110

### PR DESCRIPTION
**Pull request by TeamPearson**
resolves #1057 
resolves #1138

### CODE REVIEW

**Comment by TeamPearson** [comment]
resolves #1059

**Comment by Jawich-N** [comment]
This version of shine is much more intuitive and smooth to use than the current one

**Comment by yoonikoo** [comment]
F1 Shine is still punishable and not as strong as everyone thinks. Multishine pressure is able to be rolled out of. This only serves to help Falco with better shield pressure and as an OOS option. Combos are a lot tighter due to the fact that Shine hitbox is now on frame 1 instead of 3 and there is no invincibility. Those who have grievances against Falco having F1 Shine should first test out Falco in Nightly and then test Falco in this PR. This does not change Falco's position in any way, shape, or form. He still is able to die at 0% as he has the one of the worst disadvantages in the game. 

https://user-images.githubusercontent.com/105788245/193443050-9d27e878-fd2e-4d6f-a991-479de65c4569.mp4

**Comment by Kaiokendo661** [comment]
I was testing the f1 shine with yooni last night. The design philosophy behind the shine is very solid imo. My biggest gripe with f1 shine in HDR, however, is the 5 frames of buffer. In melee, because of the lack of buffer, theres a certain risk behind using shine as a instant counter during hitstun/chaingrabs because you have to time it frame perfectly afterwards to do it optimally (or at all if you're too early) and it balances the risk of the latter with the reward of getting the instant counter. In HDR, the risk is nullified because you get 4 extra frames to do it as soon as you leave hitstun, making it waay easier to spam it during combos as a result. I already asked in dev-general the logistics of making shine unbufferable but im not entirely sure if its possible. At the time of this I havent gotten an answer back but if its not i would be a lot more cautious about merging it into nightly. Otherwise I think the changes are fine and they feel good to use!

**Comment by TeamPearson** [comment]
Old
image

New
image

**Review by HisashiASM — DISMISSED** [review]
All seems good

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Review by WuBoytH — APPROVED** [review]

**Pull request merged**
