### PR TITLE
Pacman Hydrant Changes

### PR DESCRIPTION
**Pull request by jdipalermo27**
As hydrant stands, it incentivizes pacman to play a very non interactive game, by lowering hydrants health to 7 percent, this should force interaction and mixups by allowing pacman or the opponent to launch hydrant faster. This will nerf the move as a camping tool, but buff it as a setplay move. It also nerfs the move in disadvantage as you're essentially giving the opponent a setplay tool.

7 percent was chosen to prevent the fastest and lowest commitment projectiles from launching the hydrant.

<==Pacman==>
HYDRANT
~[R] HP: 16 --> 7
Grounded Placement
~[+] Pacman can now start drifting frame 10 of animation
~[+] FAF: 35 --> 25
Aerial Placement
~[+] Pacman can now start drifting frame 10 of animation

### CODE REVIEW

**Review by hdr-balance-backroom — CHANGES_REQUESTED** [review]
- Move the air control to opff instead of acmd and disable it on landing
- Revert the FAF change to grounded down special
- Increase hydrant HP to 10

**Comment by SuddyN** [comment]
update changelog please :)

**Comment by hdr-balance-backroom** [comment]
This still needs the air control moved to opff and disabled on landing

**Comment by jdipalermo27** [comment]
How can i put this on pause, I'm not really trying to work on this one right now.

**Pull request closed without merging**
