### PR TITLE
Little Mac adjustments

### LINKED ISSUE #517: Little Mac adjustments
<=== LITTLE MAC ===>

~ Jab 1:
~ [R] Changed ground-level hitboxes to a single capsule hitbox
~ [R] Moved ground-level hitbox upwards by 1.5 units (3.0 -> 4.5)
~ [R] Changed collision property of ground-level hitboxes to only hit grounded opponents
~ [/] Removed duplicate hitbox declarations

~ Jab 2:
~ [R] Changed ground-level hitboxes to a single capsule hitbox (angle 361, bkb 25, kbg 25)

~ Jab 3:
~ [!] Added Dreamland Express, which maintains previous Jab3 stats. Performed by pressing attack during frames 18-20 of Jab2
~ DLE
~ [=] Hitlag Multiplier: 2.0 -> 2.3
~ Normal
~ [-] Angle: 75 -> 70
~ [-] BKB: 49 -> 70
~ [-] KBG: 71 -> 84

~ Forward Tilt:
~ [-] Removed arm intangibility on hit 1

~ Up Tilt:
~ [-] Angle: 96 -> 100
~ [R] Flipped angle after frame 6
~ [-] BKB: 50 -> 70
~ [/] KBG: 90 -> 80

~ Down Tilt:
~ [-] Removed body hitboxes
~ [-] Hitbox Size (fist): 4.5 -> 4.0

~ Dash Attack:
~ [/] Hitbox Duration (early): f6-f10 -> f6-f9
~ [-] Hitbox Duration (late): f11-f19 -> f10-f11

~ Forward Smash:
~ Neutral
~ [+] Damage (sweetspot/sourspot): 16.5/14.0 -> 17.0/14.5

~ Neutral Air:
~ [-] Removed hip hitbox

~ Forward Air:
~ [-] BKB: 50 -> 60
~ [-] Hitbox Size (fist): 5.0 -> 4.5

~ Back Air:
~ [-] Hitbox Size (fist): 5.0 -> 4.5

~ Up Air:
~ [-] Angle: 80 -> 78
~ [-] KBG: 70 -> 98

~ Down Air:
~ [-] Hitbox Duration (early/late): f7-f9 / f10-f17 -> f7-f9 / f10-f13

~ Neutral Special:
~ KO Punch
~ [!] Hold taunt during startup to have Doc Louis chime in (differs per taunt)
~ [+] Shield Damage: 0 -> 2

~ Side Special:
~ [-] Removed upper body intangibility on startup (kept lower body intangibility)
~ [!] Added projectile invulnerability around upper body on frames 1-10

~ Up Special:
~ [-] Moved intangibility from f1-f3 -> f3-5
~ Initial Hit
~ [/] Split into ground-only and air-only hitboxes
~ Rise
~ [+] Added a small hitbox to the waist to mitigate grounded characters dropping out of the aerial version

~ Standing Grab:
~ [+] Startup: f8 -> f7

Images: https://imgur.com/a/iYTD7Wm

### PR DESCRIPTION
**Pull request by SkewedAskew**
Please see #517 for information
Resolves #517

### CODE REVIEW

**Comment by Riah321** [comment]
lgtm :)

**Comment by MadVillainLordQ** [comment]
Overall:
Very happy with the hitbox cleanups. Jab 3 can still effectively combo at higher percents, it just requires following DI with either side B or up B. Nicely done overall. Here are my notes.

Notes:
- Change sound effect for DLE to make it sound more impactful (maybe use kaguya ewgf thunder noise)
- Up b is still intangible frame 1-3 instead of 3-5
- I believe we can remove the body hitboxes from dtilt and only keep the arm hitboxes (basically like ultimate)
- Horizontal fsmash could use more kb. I think we can increase the damage to 17% and that may be enough to increase the kb.
- Grounded/aerial neutral b charge should have some sort of charge cancel animation. I'd suggest the animation takes 8 frames before he can act again (In line with other charge cancel animations). Currently he can shield immediately the frame after armor and in the air can potentially use attacks out of neutral B charge immediately due to the Z attack change (think yoshi DJ armor)
- Grounded side B still appears to have full body intangibility on frames 1-3

**Comment by SkewedAskew** [comment]
Intangibility on side b and up b require motion_list edits (both should be entirely removed), which only devs are able to do. I'll experiment with the other changes and update within the next day or so

**Comment by SkewedAskew** [comment]
@jobrien97 @black-calculus @techyCoder81 Please remove all intangibility on up special and side special from Little Mac's motion_list.bin when you are able

**Comment by black-calculus** [comment]
Small addendum to this PR, the attached .zip contains the motion_list.bin edits needed to remove the intangibility on Jolt Haymaker's grounded leap. These files will be merged in once this PR is merged into this repo.

For users experienced with modifying specific files of their install, merge the `fighter` folder in the attached .zip with the `fighter` folder in whatever assets folder you're using to test PRs.
[assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/8710612/assets.zip)

**Comment by black-calculus** [comment]
Small addendum to this PR, the attached .zip contains the motion_list.bin edits needed to remove the intangibility on Rising Uppercut and Jolt Haymaker's grounded leap. These files will be merged in once this PR is merged into this repo.

For users experienced with modifying specific files of their install, merge the fighter folder in the attached .zip with the fighter folder in whatever assets folder you're using to test PRs.
[assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/8710620/assets.zip)

**Review by techyCoder81 — APPROVED** [review]

**Pull request merged**
