### PR TITLE
Reimpl'd Illusion

### PR DESCRIPTION
**Pull request by WuBoytH**

### CODE REVIEW

**Comment by WuBoytH** [comment]
There's currently a weird thing where shortening Illusion in the air will not make you have any air friction. Is this intentional?

**Comment by WuBoytH** [comment]
> There's currently a weird thing where shortening Illusion in the air will not make you have any air friction. Is this intentional?

This has been fixed, the game overrides your air brake with a much smaller value, letting you drift further than normal.

**Comment by TeamPearson** [comment]
Tested this out on all three characters timing feels good.

**Review by jobrien97 — APPROVED** [review]
lgtm, tested ingame as well

**Pull request merged**
