### PR TITLE
Young link 2 hit Usmash and hitbox tweaks

### PR DESCRIPTION
**Pull request by Riah321**
Up smash is unfinished. Needs motion list changes (faf is far too late)

Assets!
[younglink-assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/12694382/younglink-assets.zip)

Follow up adjustments for Young Link, as directed by MadVillain.
Also includes a new 2 hit Up Smash!!

Changes include:

Nair Autocancel window F34 -> F31.

Fair 2 Hitlag mul 1.2 -> 1.0

Bair 1/2 hitlag mul 0.8/1.2 -> 1.0
Bair 2 knee hitbox sizes 3.5 -> 4.0.

Up air arm hitbox 3.4 -> 3.8

Dair early hitlag mul 1.2 -> 1.0

DA late hitbox launch angle 361 -> 50.
DA late hitbox BKB 20 -> 50

New two hit up smash! 
Up Smash hit 1 Damage/Hitlag/SDI mul: 3.0%/0.6x/0.5x ->5.0%/0.8x/0.4x
U Smash hit 2(was 3) Damage: 8.0% ->10.0%

Order: Nightly -> PR
Bair 2:
Screenshot 2023-07-07 162421
Screenshot 2023-07-07 161639
Up Air:
Screenshot 2023-07-07 162405
Screenshot 2023-07-07 161612

### CODE REVIEW

**Comment by yoonikoo** [comment]
Be sure to include before and after pictures of any hitbox adjustments to the PR.

**Comment by Riah321** [comment]
> Be sure to include before and after pictures of any hitbox adjustments to the PR.

Done! :)
This PR is ready for review.

**Comment by Boargerr** [comment]
This is pretty good for Young Link correcting the hitboxes and adding great changes and it doesn't make him super powerful or weak he's pretty fair and balanced and it looks good to me.

**Comment by octorox** [comment]
Looks good to me. I like the 2-hit Usmash.

**Review by hdr-balance-backroom — DISMISSED** [review]
- Remove the two hit up smash or edit the animation to have better flow between the hits
- Lower late dash attack angle to 50
- Revert dthrow for now
- Revert uair landing lag

**Comment by Riah321** [comment]
The PR is now compliant with the backroom's request

Edit: I lied, 2 hit usmash anim is on the way.

**Comment by SkewedAskew** [comment]
Is this still expecting a new animation?

**Comment by Riah321** [comment]
It's done! Thanks pear :0

**Review by WuBoytH — APPROVED** [review]

**Pull request merged**
