### PR TITLE
Snake changes

### PR DESCRIPTION
**Pull request by black-calculus**
Big batch of Snake changes for the time being. Will post the changelog and link to the updated romfs once those are up.

### CODE REVIEW

**Comment by camrentm** [comment]
Snake sticky is still falling off in normal play.

**Comment by MadVillainLordQ** [comment]
For those testing out the PR, see the attached changelog along with a gallery of the different hitbox changes done. 

[Snake PR Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/8710026/Snake.PR.Changelog.txt)
[Snake Hitbox Comparison](https://imgur.com/a/WKjspS4)

**Comment by black-calculus** [comment]
Changelog (courtesy of Mad Villain with further details filled in by me):
[Snake Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/8748968/Snake.Changelog.txt)

Old/new hitbox comparison (courtesy of Mad Villain):
https://imgur.com/a/WKjspS4

motion_list changes for Snake (to be merged in alongside this PR later):
[Snake motion list.zip](https://github.com/HDR-Development/HewDraw-Remix/files/8748972/Snake.motion.list.zip)

**Comment by black-calculus** [comment]
No other issues were reported so I am closing and merging this PR for now

**Pull request merged**
