### PR TITLE
Fix Explosion VFX Size.

### PR DESCRIPTION
**Pull request by HisashiASM**
Nothing special :), have a nice day.

### CODE REVIEW

**Comment by Riah321** [comment]
LGTM. Thank you :)

**Comment by Riah321** [comment]
LGTM. Thank you :)

**Comment by WuBoytH** [comment]
As far as I understand, something like this won't... *build*, right? You'd need something in the build script that will rename the .lua to a .lc for when the file gets packaged?

**Comment by WuBoytH** [comment]
Oh right uh move this to hdr-private.

**Pull request closed without merging**
