### PR TITLE
Bowser Jr. Adjustments

### PR DESCRIPTION
**Pull request by yoonikoo**
Bowser Jr. was in a state of oppressiveness and had values that aligned with HDR's Alpha. This brings Bowser Jr. to HDR's current philosophy.

[Bowser Jr Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/10305833/Bowser.Jr.Changelog.txt)

Make sure to download the necessary ROMFS changes. 

[hdr-assets-dev.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10291143/hdr-assets-dev.zip)

In order to do so, copy these changes to the hdr-assets folder in the mods directory, and save a copy of the folder before merging these changes in (these will change koopajr values that are currently in nightly.)

### CODE REVIEW

**Comment by kalomaze** [comment]
Mechakoopa travel nerfs aren't working according to Rektangles, I can verify on my install as well

**Review by SkewedAskew — DISMISSED** [review]
Lgtm

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Review by SkewedAskew — APPROVED** [review]
Lgtm again

**Pull request merged**
