### PR TITLE
King K. Rool Adjustments

### PR DESCRIPTION
**Pull request by MadVillainLordQ**
King K. Rool has received some frame data and run speed adjustments. Future adjustments are planned for blunderbuss, gut check, and crownerang.

Notes:

- Dsmash can now slide off ledges when performing a DACDS
- Crownerang's heavy armor has been replaced with belly armor
- Dtilt bury has been replaced with a meteor sweetspot
- Dthrow bury has been replaced with a knockdown throw
- Can no longer wall jump

[Hitbox Old vs. New Comparisons](https://imgur.com/a/1AO9VMQ)
[King K. Rool PR Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/9730072/King.K.Rool.PR.Changelog.txt)

### CODE REVIEW

**Comment by yoonikoo** [comment]
Jab can now act as a tick. Jab 1 to grab is more viable for K. Rool. Ftilts adjustment was warranted. With it being a 12 frame start up now, you still get belly armor from frames 7-11. This makes the first 6 frames punishable still, which is in my opinion, healthy for a heavy character. Up-tilt comes at at frame 5 and ends on frame 22. You can initiate a jump at frame 55 of the move. This was too strong of a move pre-PR and had a vacuum hitbox. As a heavy, K. Rool should have hard hitting moves and slow actionable frames. With D-tilt being a meteor on the floor now, this allows K. Rool to converge into combo routes from it. Pair this with the new Dthrow, you now have tech chase situations. His aerials were very strong walling tools and was warranted a nerf as they were both fast and strong. With K. Rools defined as a true heavy, these changes are very healthy for the game and for the character. Power was shifted away from his actionability into his damage. K. Rool now has sauce with his DACDUS and can be truly punished and can be punished as a heavy.

**Comment by yoonikoo** [comment]
https://user-images.githubusercontent.com/105788245/194690100-e1032767-cb06-48bc-991d-cf0219007f7d.mp4

**Comment by yoonikoo** [comment]
https://user-images.githubusercontent.com/105788245/194690147-b9cf415d-0427-4288-8368-96b861c615ae.mp4

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Review by WuBoytH — DISMISSED** [review]

**Review by WuBoytH — APPROVED** [review]

**Pull request merged**
