### PR TITLE
Ridley rework

### PR DESCRIPTION
**Pull request by SkewedAskew**
Many thanks to AParticularUser for allowing us to incorporate Ridley Improved! This rework contains many significant adjustments to Ridley's moveset that give him some real HDR seasoning

Changelog: [Ridley-changes.txt](https://github.com/HDR-Development/HewDraw-Remix/files/10306574/Ridley-changes.txt)

Romfs: [hdr-assets-pr.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10254874/hdr-assets-pr.zip)
Update the config.json in hdr-assets with this (or place it inside the hdr-assets-pr folder): [config.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10254934/config.zip)

Hitbox Comparisons (slightly outdated in some aspects): https://imgur.com/a/nMvTlGJ

https://user-images.githubusercontent.com/55216313/208131076-2643c9ce-4676-480c-80c5-5636c3a01836.mp4

### CODE REVIEW

**Comment by yoonikoo** [comment]
Ridley feels like a true boss character how. With iconic moves such as tail sweep and skewer, there is more reason to respect him in the air. Though there are plans for animation fixes, it LGTM.

**Comment by yoonikoo** [comment]
Tested the new changes while getting bodied by Askew. LGTM

**Review by MadVillainLordQ — DISMISSED** [review]
LGTM

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Review by techyCoder81 — APPROVED** [review]

**Pull request merged**
