### PR TITLE
Krool armor overhaul

### PR DESCRIPTION
**Pull request by SkewedAskew**
A rework of kolossal proportions

Assets (no longer needed thanks to motion patching): [assets-krool.zip](https://github.com/HDR-Development/HewDraw-Remix/files/11841103/assets-krool.zip)

### Belly Armor:
- (!) Belly armor now depletes based on number of hits instead of by damage
  - (!) Krool can armor any amount of damage in a single hit up to four times
- (!) Absorbing hits with the belly armor stores damage to be used with Gut Check
  - (!) After armoring an attack, the belly armor becomes inactive for the rest of the current move
- (!) If the incoming damage deals less than 4.0% then the armor will not be depleted
- (!) Krool can now charge his tilts for up to 18 frames to extend the armor's duration
  - (!) Tilts scale damage, hitlag, and shieldstun with charge, up to an additional 3.0%, 0.5x, and 0.4x respectively at max charge
- [+] Krool is no longer forced into a shieldbreak when the armor is destroyed
- [-] Belly armor no longer regenerates over time
- [+] Belly detection area reshaped and increased to cover all of Krool's midsection

### Forward Tilt:
- [$] Adjusted vfx
- [$] Changed sweetspot sfx when above half charge
- [-] Belly Armor Duration: F5-11 -> F9-11

### Up Tilt:
- (!) Added belly armor
- (!) Belly Armor Duration: F6-8
- [-] Hitbox Duration (early/late): F5-7/F8-13 -> F9-11/F12-17

### Down Tilt:
- (!) Added belly armor
- (!) Belly Armor Duration: F10-12
- [+] Front leg given intangiblity during frames 5-12
- Early
  - [+] Can now hit aerial opponents
  - Ground-only
    - [R] Angle: 361 -> 270
    - [R] BKB: 40 -> 100
    - [R] KBG: 85 -> 35
  - Air-only
    - Damage: 13.0%
    -  Angle: 361
    -  BKB: 40
    -  KBG: 85
    -  Hitbox Size: 5.0u

### Forward Smash:
- (!) Added belly armor
- (!) Belly Armor Duration: F12-16

### Neutral Air:
- [-] Belly Armor Duration: F6-30 -> F7-30

### Up Air:
- [-] Removed belly armor
- [/] Hitlag Multiplier (early): 1.3x -> 1.0x

### Down Air:
- [-] Removed belly armor
- [/] Hitboxes moved upwards 2.0u
- [+] Added chest hitbox
  - Hitbox Size (early/late): 6.5/6.0u
- [$] Adjusted vfx

### Blunderbuss:
- (*) Fixed issue where Krool would immediately enter the "spit" animation when trying to inhale the Kannonball
- (!) Hold Attack or Shield during startup to suck in opponents instead of firing a Kannonball
- [R] The suction when holding Special after firing a Kannonball now only interacts with the Kannonball
- [+] Significantly increased the range that Krool is able to interact with the Kannonball
- [+] Airspeed Multiplier: 0.8x -> 0.85x
- [+] Fallspeed Multiplier: 0.8x -> 1.0x
- Blunderbuss Fire
  - [+] Startup: F25 -> F23
  - [+] FAF: 65 -> 60
- Blunderbuss Grab
  - Startup: F25
- Kannonball
  - [+] Lifetime: 120F -> 150F
  - [-] Shield Damage: 0.0% -> -2.0%
- Forward Throw
  - [+] Damage: 12.0% -> 16.0%
  - [=] BKB: 75 -> 78
  - [=] KBG: 69 -> 54
  - [+] FAF: 34 -> 29
- Back Throw
  - [+] Damage: 12.0% -> 16.0%
  - [+] BKB: 75 -> 78
  - [+] KBG: 48 -> 54
  - [+] FAF: 47 -> 42

### Krownerang:
- [R] Belly armor changed to light armor
  - Armor Knockback Threshold: 180KB
- [+] Armor Duration: F6-14 -> F6-17

### Gut Check:
- (!) Redesigned as a chargeable shine
- (!) Fully charging Gut Check will add a portion of all damage stored via armoring hits to the attack and restore the armor to max health on hit
  - (!) Stored damage is lost when connecting with a charged Gut Check or on stock loss
- (!) Can be B-reversed
- Non-charged
  - (!) Can be jump canceled on frame 10
  - Hitbox Duration: F7
  - Damage: 7.0%
  - Angle: 69
  - BKB: 70
  - KBG: 90
  - Hitbox Size: 9.0u
- Charged
  - Hitbox Duration: F30-32
  - Damage (no storage/max storage): 16.0/25.0%
  - Angle: 50
  - BKB: 50
  - KBG: 90
  - Hitbox Size: 10.5u
- FAF: 42

### Down Taunt:
- (!) Added a hitbox that trips nearby opponents
- Hitbox Duration: F20-21
- Damage: 8.0%
- Angle: 361
- FKB: 30
- KBG: 43
- Hitbox Size: 3.5u

Screenshot 2023-07-04 19-17-43
Screenshot 2023-07-04 18-50-57

### CODE REVIEW

**Review by jobrien97 — DISMISSED** [review]
blip

**Review by jobrien97 — DISMISSED** [review]
Love Gaming Too Much

**Comment by jobrien97** [comment]
nvm fix those conflicts ya bum

**Comment by SkewedAskew** [comment]
> nvm fix those conflicts ya bum

Yes mother

**Review by jobrien97 — DISMISSED** [review]

**Review by blu-dev — APPROVED** [review]

**Pull request merged**
