### PR TITLE
Newer Lucas Just Dropped

### PR DESCRIPTION
**Pull request by HisashiASM**
Requires assets for animation and frame adjustments: 
[lucas-assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10430526/lucas-assets.zip)
- Increased angle of nair from 40 to 50
- Changed location of nair sweet by 2.2 units forward and reduced its size dramatically.
- Readjusted Logic of DSmash1 and added DSmash2
- Decreased Damage of DSmash 1 and 2 for non-OU
- Made PKT not die in Blastzone and have a smaller collisionbox (NOT HITBOX)
- Changed Lucas's run_accel_mul 0.04 > 0.1 (allowing moonwalking)
- Added 5 frames to air pkf to stop wavelanding (sorry ilovebagelz)
- Allows Kirby to call back to PK Freeze Original (Sorry, no OU for that little guy yet)
- Up Special Cancel Removed
- Grab sped up 69>48
- Dash Grab sped up 79>62
- Zair early sweet sends in now.
- Zair landing lag increased 21>23.
- Grab hitboxes were fixed.

### CODE REVIEW

**Comment by HisashiASM** [comment]
Make a clone of hdr-assets and drag and overwrite this onto it, then disable hdr-assets and enable your clone.
[lucas_files.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10368058/lucas_files.zip)

**Comment by HisashiASM** [comment]
Make a clone of hdr-assets and drag and overwrite this onto it, then disable hdr-assets and enable your clone.
[lucas_files.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10370011/lucas_files.zip)

**Comment by ValistaBarista** [comment]
These changes are fantastic. OU looks great, having the option to do double down Smash is awesome. The turn around not lasting forever is a game changer for me even more than the ability to moonwalk which is also awesome! Nair being nerfed is fair, and thunder not being instantly being eaten by walls and the blast zone makes this character feel so much more complete! Great job Hisashi!

**Comment by hdr-balance-backroom** [comment]
- Re-evaluate zair's ability to pull inwards on the tipper
- Move inner hitbox of launcher hit of nair forward and reduce the size so reverse hits depend more on Lucas's drift

**Comment by HisashiASM** [comment]
Make a clone of hdr-assets and drag and overwrite this onto it, then disable hdr-assets and enable your clone. Or use the hdr-launcher 0.3.3 or higher
[lucas-assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10421929/lucas-assets.zip)

**Review by SkewedAskew — APPROVED** [review]
Lgtm

**Pull request merged**
