### PR TITLE
Bowser Jr Re-evaluation

### PR DESCRIPTION
**Pull request by yoonikoo**
Cleaning up some motion rate calls and fixing inconsistencies with the character. Just simple changes.

<== BOWSER JR (Glue-eating Child)==>

GROUND

-Jab 1
~[-] No longer drags opponents towards Bowser Jr.

-Jab 2
~[-] Removed the added 3f hitstun

AERIALS

-NAIR
~[-] FAF increased from 36 to 40

-DAIR
~[R] Removed the last "launcher" hitbox as it functioned the same as the rest of the move

-BAIR
~[-] Autocancel Frame Window: 34 -> 38

-UAIR
~[-] Autocancel Frame Window: 16 -> 35
~[-] Decreased hitbox sizes from 4.0 to 3.0

TILTS

-DTilt
~[-] Removed the 1.2x shieldstun multiplier
~[+] Added body hitbox for consistency 

-UTilt
~[R] Angle changed from 105 to 95
~[+] KBG changed from 85 to 75

THROWS

-DThrow
~[R] Angle changed from 30 to 275
~[+] FAF decreased from frame 78 to 72

SPECIALS

-Side B
~[R] Comes out frame 4 instead of 3 to prevent instashield break/instakill bug

Hitboxes:

-Down Tilt
Before
Downtilt Nightly
After
Downtilt PR

-Up Air
Before
UpAir Nightly
After
UpAir PR

### CODE REVIEW

**Review by hdr-balance-backroom — CHANGES_REQUESTED** [review]
Down throw needs the proper knockback and flags in line with other knockdown throws (see Incineroar, Krool, Kirby, etc)

**Comment by yoonikoo** [comment]
> Down throw needs the proper knockback and flags in line with other knockdown throws (see Incineroar, Krool, Kirby, etc)

Committed the following changes.

**Comment by yoonikoo** [comment]
> Down throw needs the proper knockback and flags in line with other knockdown throws (see Incineroar, Krool, Kirby, etc)

Done

**Comment by yoonikoo** [comment]
> Down throw needs the proper knockback and flags in line with other knockdown throws (see Incineroar, Krool, Kirby, etc)

Done

**Review by hdr-balance-backroom — DISMISSED** [review]
- Please verify the autocancel windows for all aerials, as they will be altered by JOB's ECB change and may need fixing
- Revert bair autocancel frame to its original frame in acmd, and instead use motion rates to match the autocancel window to when the wrecking ball finishes retracting into the clown car

**Review by SuddyN — APPROVED** [review]

**Pull request merged**
