### PR TITLE
Brawler Specials Rework

### PR DESCRIPTION
**Pull request by chrispo-git**
assets: [mii_brawler_hdr_assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/11198668/mii_brawler_hdr_assets.zip)

Neutral Special 2 - Flashing Mach Punch:
[+] Startup: F10 -> F7
[+] Final Hit Damage: 9.5% -> 10.5%
[+] Final Hit Angle: 75 -> 77

Side Special 1 - Onslaught:
[+] Animation timing adjusted; Brawler accelerates faster
[+] Onslaught now activates on shields
[+] Aerial Onslaught no longer goes into freefall on hit, with an FaF of 61
[-] Onslaught final hit damage 7% -> 4%
[+] Onslaught final hit BKB 58/54 (Ground/Aerial) -> 80/60
[+] Onslaught final hit KBG 144/130 (Ground/Aerial) -> 175/160

Side Special 2 - Burning Dropkick:
[+] Fixed BDK momentum bug

Up Special 2 - Helicopter Kick:
Helicopter Kick is more consistent:
[+] Grounded Hit 1 FKB 70 -> 90
[+] Aerial Hit 1 Angle 75 -> 367/80/366 (Air/Ground Upper/Ground Lower)
[+] Grounded Hit 1 FKB 100/75
[=] Start Speed Y: 2.3 -> 2.22
[=] Start Gravity: 0.385 -> 0.4
Aerial Hit 1 Hitboxes altered:
[-] Hitbox Size: 4.0/6.5 (Upper/Lower) -> 4.5
[+] Hitbox Z offset: 6.0/6.5 (Upper/Lower) -> 6.0/3.0
[=] Hitbox Y offset: 14.0/9.0 (Upper/Lower) -> 13.5/6.5

Brawler has 2 new Down Specials:

Down Special 1 - Earthquake Fist:
On the ground, Brawler creates a shockwave on the ground. Holding B allows the shockwave to happen further away.
In the air, Brawler dives diagonally. A second B press stops this move

Grounded Stats:
Startup - 13-28
FaF on release - 35 (42 uncharged, 57 max charge)
Damage - 18%/16% (Sweetspot/Sour)
BKB - 80/82 (Sweetspot/Sour)
KBG - 48/53 (Sweetspot/Sour)
Angle - 80
Active Frames - 13/13-14 (Sweetspot/Sour)

Aerial Stats:
Startup - 15
Landing Lag - 31/29 (Uncancelled/Cancelled)
Damage - 15%/14% (Fall/Landing)
BKB - 80/120 (Fall/Landing)
KBG - 57/48 (Fall/Landing)
Angle - 361/60 (Fall/Landing)
Can Snap Ledge from Frame 15

Down Special 3 - Wild Throw:
Brawler grabs the opponent and slams them into the ground, causing a techchase situation on the ground or spiking them in the air
FaF - 53/39/55 (Grab/Grounded/Aerial)
Damage - 10%/14% (Grounded/Aerial)
BKB - 10 (Aerial)
KBG - 65 (Aerial)
Angle - 280

### Helicopter Kick
Old
hk_old

New
hk_new

### Wild Throw Grabbox
wild_throw

### Grounded Earthquake Fist
minimum range
fist_min_new

max range
fist_max_new

### Aerial Earthquake Fist
Fall
air_earthquake_fist_fall

Landing
air_earthquake_fist_land

### CODE REVIEW

**Comment by MosaMosa-x** [comment]
The brawler special rework is a great step in the right direction for brawler's kit finally fixing some of the bigger issues with his specials as well as giving him new options with Wild Throw and Earthquake Punch.

FMP finally feels like the combo finisher it was meant to be it being frame 7 is a huge change and makes linking into it so much more consistent, The fixes to Helicopter Kick and Burning Dropkick finally make the moves useable with them properly connecting and giving Brawler the options he needs against FFs. Onslaught is now a move worth using with the buffs it has gotten now being able to use it to possibly shield break and it being fast enough to confirm from falling aerials and grabs is great.

Wild throw is a very interesting move and gives brawler a new way to play the game. although it is kinda hard to hit, it's justified with the follow-ups and mix he gets from it. Not to mention he can dunk people off the stage and I do feel like maybe at some point it may have to get toned down (at least the aerial version) but for right now it's great.

Earthquake Punch I'm a bit less sold on, I feel like it's really close to being a great move for brawler. but its knockback is in this weird middle ground where its a bit too high to combo from it reliably but also low enough to where it's not gonna kill and the angle while it sending straight up is nice, but I do kinda wish it sent move inwards towards brawler at least for the charge version of the move. The Aerial version of Earthquake Punch is great though, it's a really strong option and the cancel makes it hard to challenge on Shield. The only thing I would want from it is being able to edge cancel or even just wall jump from it as it does just send you to your death.

Overall I think the changes to Brawler are very fun changes and open up a lot for the character. I would love to see these merge into nightly soon and maybe some more touch ups in the future, Great changes

**Review by SuddyN — DISMISSED** [review]
lets convert all these `FT_MOTION_RATE` to the standard format `FT_MOTION_RATE(fighter, C / (B - A))`, especially since this ACMD is already so complex. Other than that, LGTM and very excited to try these out!

**Review by hdr-balance-backroom — DISMISSED** [review]
Onslaught should be once per airtime if not entering special fall on whiff

**Comment by chrispo-git** [comment]
> Onslaught should be once per airtime if not entering special fall on whiff

Onslaught already still puts you into special fall on whiff in the PR

**Comment by chrispo-git** [comment]
> lets convert all these `FT_MOTION_RATE` to the standard format `FT_MOTION_RATE(fighter, C / (B - A))`, especially since this ACMD is already so complex. Other than that, LGTM and very excited to try these out!

I've updated the startup of FMP and wild throw's motion rates to the standard format, but the rest of the FT_MOTION_RATEs are straight from vanilla's code, so idk how exactly they're supposed to be

**Review by SkewedAskew — APPROVED** [review]

**Pull request merged**
