### PR TITLE
Banjo - remove feather dthrow

### LINKED ISSUE #736: Banjo - remove feather dthrow
As voiced by others, a bit too weak to justify a feather usage

### PR DESCRIPTION
**Pull request by jobrien97**
Banjo can no longer hold dthrow to bury the opponent at the expense of a feather.
It is now a normal throw.

Resolves #736

### CODE REVIEW

**Comment by kalomaze** [comment]
Does this have a lucas esque fake bury?

**Comment by jobrien97** [comment]
> Does this have a lucas esque fake bury?

No, opponent just bounces up. It's the same as current nightly light dthrow

**Comment by kalomaze** [comment]
Hmm if possible I would like to see a fake bury, it would fit the animation way more than banjo slamming someone into the ground with his fists shut and them just popping up

**Review by WuBoytH — APPROVED** [review]
LGTM

**Pull request merged**
