### PR TITLE
King K. Rool changes

### PR DESCRIPTION
**Pull request by black-calculus**
Big batch of K. Rool changes for the time being. Will post the changelog and link to the updated romfs once those are up.

### CODE REVIEW

**Comment by Riah321** [comment]
image
Got this on boot.

**Comment by jobrien97** [comment]
I'm personally against the concept of light/heavy tilts, but the PR functions as expected
Hold B to catch crown is also not a great input, it's very easy to accidentally catch crown. Perhaps there's another input we can try

**Comment by techyCoder81** [comment]
very hard agree on heavy tilts not making sense 99.9% of the time in the context of smash bros - they are called smash attacks

**Comment by Riah321** [comment]
Any chance all this could be revisited soon? Aside from the heavy tilts I'm pretty curious what else is in here. Also wouldn't hurt anyways since krool is a little overtuned in some areas.

**Pull request closed without merging**
