### PR TITLE
Fix JC usmash logic

### LINKED ISSUE #918: Reimplement Jump Cancel Up Smash
In Vanilla, if you enter jumpsquat, release the jump button, and press A while holding Up, you will *always* get an Up Smash. This will be updated so that it will instead only work if the stick has been flicked upwards, instead of needing to be tilted up at all.

### PR DESCRIPTION
**Pull request by WuBoytH**
In Vanilla, if you have up held on the left stick for any amount of time, enter jumpsquat, let go of jump and press A, you will always get usmash.
Now you must flick the stick to get a JC usmash. (this makes stuff like buffered uairs easier)

Resolves #918

### CODE REVIEW

**Comment by Riah321** [comment]
JC item toss logic should be as follows

Option 1: (preferred for ease of use) Remove JC item toss, make any toss during JS buffer the air version
Option 2: (preferred for depth) Any item toss input while holding jump during JS will buffer the air version. Item toss after releasing jump will input the grounded toss varient. This allows for buffered full hop _and_ short hop item tosses, as well as JC tosses

Otherwise looks solid to me :)

**Comment by jobrien97** [comment]
In Vanilla, if you have up held on the left stick for any amount of time, enter jumpsquat, let go of jump and press A, you will always get usmash.
Now you must flick the stick to get a JC usmash. (this makes stuff like buffered uairs easier)

**Review by techyCoder81 — APPROVED** [review]
looks pretty simple to me, just should be tested

**Comment by jobrien97** [comment]
Tested ingame, works

**Pull request merged**
