### PR TITLE
Inkling adjustments.

### PR DESCRIPTION
**Pull request by Riah321**
Mainly hitbox cleanup with some slight reduction of kill power across the board to incentivize more precision and prevent kills at 75% off the top.
~~Slight adjustments to this PR and a changelog will be provided soon.~~ It's done! 
Needs in game testing for QA before being merged.

Below are outdated.
~~Changelog fixed and attached!~~
~~[Inkling Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/9186736/Inkling.Changelog.txt)~~

~~Hitbox comparison!~~
~~https://imgur.com/a/IyW6T4a~~

### CODE REVIEW

**Comment by Riah321** [comment]
[Inkling Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/9179373/Inkling.Changelog.txt)

**Comment by SkewedAskew** [comment]
A couple things here:
- What is the reason for the slight knockback reduction on ftilt?
- Why remove late hit nair? Making the entire move a sex kick with the properties of the early hit is not a good idea
- Does sweetspot fsmash really need a buff/sourpot need a nerf?
- Please reduce the kbg on sweetspot up smash, it's entirely too strong now

As for hitboxes, I'll need to see comparisons to make further judgements

**Comment by SkewedAskew** [comment]
Lgtm

**Comment by MadVillainLordQ** [comment]
General Notes:

- Jab 3 can be reverted back to previous hitbox size and a slightly lower position. You may have only been looking at the first frame of jab 3, but in the frames after, inklings foot expands its size.
- Fair sweetspot hitlag modifier does not need to be increased to 1.05
- Bair hitbox sizes were reduced to 3.5 and as seen in hitbox comparisons, don't really cover the visual well. The size can be lowered from its current 4.5 to 4.0 and matched in the same spots it currently has. Removal of the extra hitboxes is fine. There's no need for any kbg reduction as well.
- Please add ink to the following hitboxes: Tipper Bair and Tipper Ftilt. The values should be 20 and 35 respectively (Use the attack module code for dair)
- Remove the ink code for non tipper dair and increase the value from 10 -> 50
- Increase initial utilt angle from 95 -> 104 and decrease late hit from 85 -> 76. We leave the exact numbers to your discretion but try to more or less matchup inklings utilt kb to that of little mac utilt

**Review by WuBoytH — DISMISSED** [review]

**Comment by Riah321** [comment]
I've made some minor adjustments at madvillain's request. I'll get to the visual half of the bair ink later.

**Comment by Riah321** [comment]
Gaming Gamer

**Comment by WuBoytH** [comment]
Closed due to inactivity - reopen if work picks up again.

**Pull request closed without merging**
