### PR TITLE
Yink Adjustments

### PR DESCRIPTION
**Pull request by yoonikoo**
Yink had too big of a jug of milk for milking. Less milking for the milk man.
[YL changelog true.txt](https://github.com/HDR-Development/HewDraw-Remix/files/9848418/YL.changelog.true.txt)

Currently Nightly:
2022102222360600-0E7DF678130F4F0FA2C88AE72B47AFDF
2022102222360800-0E7DF678130F4F0FA2C88AE72B47AFDF
2022102222360900-0E7DF678130F4F0FA2C88AE72B47AFDF

New PR
2022102318463600-0E7DF678130F4F0FA2C88AE72B47AFDF
2022102318463900-0E7DF678130F4F0FA2C88AE72B47AFDF
2022102318464300-0E7DF678130F4F0FA2C88AE72B47AFDF

### CODE REVIEW

**Comment by hdr-balance-backroom** [comment]
- The back arm hitboxes on fair should be moved to the sword arm (you probably only need one of those hitboxes and can remove the second one)
- Remove the pop-up of the second hit of fair when missing the first hit (it should now only launch opponents away)
- The endlag after releasing held dair is only 8 frames, you'll need to move back the frame that the release transitions into to frame 60 instead of 68 (look at the held dair function in opff)

**Review by SkewedAskew — DISMISSED** [review]
Lgtm

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Review by MadVillainLordQ — APPROVED** [review]
LGTM

**Pull request merged**
