### PR TITLE
Zelda adjustments

### PR DESCRIPTION
**Pull request by SkewedAskew**
Further experimentation and refinement

Changelog: [Zelda-changes.txt](https://github.com/HDR-Development/HewDraw-Remix/files/10109419/Zelda-changes.txt)

Romfs: [hdr-assets-pr.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10038460/hdr-assets-pr.zip)

Hitbox Comparisons: https://imgur.com/a/Fkp3YLZ

### CODE REVIEW

**Comment by Z-hime** [comment]
Huge Quality update.
Much more viable, more engaging and more fun to set traps with.
Enormous amount of potential within its framework and can be tuned up or down as needed according to power-levels in the game.

Shining points 👍

:Normals:
Fair - high precision -> high reward - (still unsure if the sweetspot, now 1F active, is big enough to be reliable against characters as combo finisher but when it actually hits, it works as in intended and works well.
Bair - Less precision -> appropriate reward and kill power for accuracy needed
Ftilt - Great angle change, leading into kill setups which she was severely lacking in previous versions
Nair - Great approach tool, now more usable against a wider range of the cast
Utilt - Currently in good standing in KB values to provide as a useful combo tool

:Specials:
SUPER mobile and able to fight.
UpB - Shorten/Cancel is a huge improvement to her zoning and trap capabilities.
SideB - Amazing. Great potential for devastating combos that rival the upper tier characters. Allows you to create a pressure zone/opportunity while remaining mobile with the UpB synergy cancels.
DownB - Extended timer is a nice touch to remind opponents not to leave zelda too much breathing room, works well to fill in gaps where she otherwise cannot secure an opening. Cancel is useful and niche for swag.
NeurtalB - Aerial inv removed is good and a healthy compensation for the addition of landcancel being that the startup frames are inv for quite some time.

:Minor concerns:
Side b - as it stands can be quite abusable with the landcancel itself allowing ~3 fireballs.
[+]Possible remedy would be to add a limiter to disable to preferably 2, or 1 fireball as discussed with Askew.
[-]Work-around would be to remove the landcancel and require the upb cancel to gain the additional timing to act before explosion.
*My preference would be to implement a limit to 2 fireball keeping the land cancel and upb cancel intact


Amazing build overall, and super polished.
Will continue further testing with this build and playing with others to gauge its effectiveness at higher levels.

<3 Zhime

**Comment by hdr-balance-backroom** [comment]
Discussion notes:
- Remove up special cancel out of side special. It heavily encourages disengagement via loops of Din's Fire -> teleport to run away. Up special being omnidirectional makes it even more difficult to punish her during this situation
- Explore a way to make Din's Fire disappear when hitting Zelda similar to how phantom works
- Potentially decrease walk/run accel
- Look into lengthening phantom's stage 3 and 4 distance by a small amount

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Review by MadVillainLordQ — APPROVED** [review]
LGTM

**Pull request merged**
