### PR TITLE
Little Mac adjustments

### LINKED ISSUE #1231: Little Mac's Dreamland Express no longer possible
In the latest release, v0.25.1, it seems that Little Mac can no longer do the input for Dreamland Express. I would assume this is most likely due to the changes recently made to Jab, but I don't know for sure.

### PR DESCRIPTION
**Pull request by SkewedAskew**
(Finally) adds a cancel animation to Straight Lunge, alongside other adjustments

Changelog: [LittleMac_changes.txt](https://github.com/HDR-Development/HewDraw-Remix/files/10702299/LittleMac_changes.txt)

[assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10702298/assets.zip)

### CODE REVIEW

**Comment by hdr-balance-backroom** [comment]
APPROVED

**Comment by Riah321** [comment]
Please increase nair startup from 3F -> 4F. It's something often complained about my cross and myself since the answer to many combos is to mash A

**Comment by SkewedAskew** [comment]
Sir, this is a draft PR from two months ago

**Comment by Riah321** [comment]
How did I get here

**Comment by Riah321** [comment]
Where am I?

Help! I'm trapped in a draft PR!

**Comment by SuddyN** [comment]
Slip Counter losing the crumple effect is a disappointing loss of character. In my opinion, the crumple effect is not toxic on its own - but the counter window was enormous, causing easy counters that lead to strong punishes. Can we not make this move more fair by tightening the counter window, so that it's somewhere between a parry and incineroar's revenge?

**Review by WuBoytH — APPROVED** [review]
Needs more comments

**Pull request merged**
